//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:11:10 PM EEST 
//


package com.epam.triimob.netbiscuits.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authentication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authentication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="api_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cache_keys">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ckey2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ekey2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="expiration2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="geography_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authenticity_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ams_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chat_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="must_change_password" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="start_channel_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reuters_channel_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="time_zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="registered_timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date_format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="campaign_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="current_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="eula_accepted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="messaging_disabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mobilize_playlist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="transcript_disclaimer_accepted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="remember_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="global_admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="support_role_level_1" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="support_role_level_2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="first_time_video">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="channel_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="last_login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="version" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="channel_membership">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="channel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="member" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="access_rights">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="desktop_studio" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="low_bandwidth_streams" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="max_bandwidth">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="bitrate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="bandwidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authentication", propOrder = {
    "apiToken",
    "cacheKeys",
    "userId",
    "alias",
    "login",
    "email",
    "name",
    "firstName",
    "lastName",
    "phoneNumber",
    "company",
    "geographyId",
    "status",
    "authenticityToken",
    "amsToken",
    "chatToken",
    "mustChangePassword",
    "startChannelId",
    "reutersChannelId",
    "timeZone",
    "registeredTimezone",
    "dateFormat",
    "jobRole",
    "campaignId",
    "currentTime",
    "eulaAccepted",
    "messagingDisabled",
    "mobilizePlaylist",
    "transcriptDisclaimerAccepted",
    "rememberToken",
    "globalAdmin",
    "supportRoleLevel1",
    "supportRoleLevel2",
    "firstTimeVideo",
    "lastLogin",
    "userType",
    "versions",
    "channelMembership",
    "accessRights",
    "lowBandwidthStreams",
    "maxBandwidth"
})
public class Authentication {

    @XmlElement(name = "api_token", required = true)
    protected String apiToken;
    @XmlElement(name = "cache_keys", required = true)
    protected Authentication.CacheKeys cacheKeys;
    @XmlElement(name = "user_id")
    protected int userId;
    @XmlElement(required = true)
    protected String alias;
    @XmlElement(required = true)
    protected String login;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "first_name", required = true)
    protected String firstName;
    @XmlElement(name = "last_name", required = true)
    protected String lastName;
    @XmlElement(name = "phone_number")
    protected int phoneNumber;
    @XmlElement(required = true)
    protected String company;
    @XmlElement(name = "geography_id")
    protected int geographyId;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "authenticity_token", required = true)
    protected String authenticityToken;
    @XmlElement(name = "ams_token", required = true)
    protected String amsToken;
    @XmlElement(name = "chat_token", required = true)
    protected String chatToken;
    @XmlElement(name = "must_change_password")
    protected boolean mustChangePassword;
    @XmlElement(name = "start_channel_id")
    protected int startChannelId;
    @XmlElement(name = "reuters_channel_id")
    protected int reutersChannelId;
    @XmlElement(name = "time_zone", required = true)
    protected String timeZone;
    @XmlElement(name = "registered_timezone", required = true)
    protected String registeredTimezone;
    @XmlElement(name = "date_format", required = true)
    protected String dateFormat;
    @XmlElement(name = "job_role", required = true)
    protected String jobRole;
    @XmlElement(name = "campaign_id", required = true)
    protected String campaignId;
    @XmlElement(name = "current_time", required = true)
    protected String currentTime;
    @XmlElement(name = "eula_accepted")
    protected boolean eulaAccepted;
    @XmlElement(name = "messaging_disabled")
    protected boolean messagingDisabled;
    @XmlElement(name = "mobilize_playlist")
    protected boolean mobilizePlaylist;
    @XmlElement(name = "transcript_disclaimer_accepted")
    protected boolean transcriptDisclaimerAccepted;
    @XmlElement(name = "remember_token", required = true)
    protected String rememberToken;
    @XmlElement(name = "global_admin")
    protected boolean globalAdmin;
    @XmlElement(name = "support_role_level_1")
    protected boolean supportRoleLevel1;
    @XmlElement(name = "support_role_level_2")
    protected boolean supportRoleLevel2;
    @XmlElement(name = "first_time_video", required = true)
    protected Authentication.FirstTimeVideo firstTimeVideo;
    @XmlElement(name = "last_login", required = true)
    protected String lastLogin;
    @XmlElement(name = "user_type", required = true)
    protected String userType;
    @XmlElement(required = true)
    protected Authentication.Versions versions;
    @XmlElement(name = "channel_membership", required = true)
    protected Authentication.ChannelMembership channelMembership;
    @XmlElement(name = "access_rights", required = true)
    protected Authentication.AccessRights accessRights;
    @XmlElement(name = "low_bandwidth_streams")
    protected boolean lowBandwidthStreams;
    @XmlElement(name = "max_bandwidth", required = true)
    protected Authentication.MaxBandwidth maxBandwidth;

    /**
     * Gets the value of the apiToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiToken() {
        return apiToken;
    }

    /**
     * Sets the value of the apiToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiToken(String value) {
        this.apiToken = value;
    }

    /**
     * Gets the value of the cacheKeys property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.CacheKeys }
     *     
     */
    public Authentication.CacheKeys getCacheKeys() {
        return cacheKeys;
    }

    /**
     * Sets the value of the cacheKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.CacheKeys }
     *     
     */
    public void setCacheKeys(Authentication.CacheKeys value) {
        this.cacheKeys = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     */
    public int getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     */
    public void setPhoneNumber(int value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the geographyId property.
     * 
     */
    public int getGeographyId() {
        return geographyId;
    }

    /**
     * Sets the value of the geographyId property.
     * 
     */
    public void setGeographyId(int value) {
        this.geographyId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the authenticityToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticityToken() {
        return authenticityToken;
    }

    /**
     * Sets the value of the authenticityToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticityToken(String value) {
        this.authenticityToken = value;
    }

    /**
     * Gets the value of the amsToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmsToken() {
        return amsToken;
    }

    /**
     * Sets the value of the amsToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmsToken(String value) {
        this.amsToken = value;
    }

    /**
     * Gets the value of the chatToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChatToken() {
        return chatToken;
    }

    /**
     * Sets the value of the chatToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChatToken(String value) {
        this.chatToken = value;
    }

    /**
     * Gets the value of the mustChangePassword property.
     * 
     */
    public boolean isMustChangePassword() {
        return mustChangePassword;
    }

    /**
     * Sets the value of the mustChangePassword property.
     * 
     */
    public void setMustChangePassword(boolean value) {
        this.mustChangePassword = value;
    }

    /**
     * Gets the value of the startChannelId property.
     * 
     */
    public int getStartChannelId() {
        return startChannelId;
    }

    /**
     * Sets the value of the startChannelId property.
     * 
     */
    public void setStartChannelId(int value) {
        this.startChannelId = value;
    }

    /**
     * Gets the value of the reutersChannelId property.
     * 
     */
    public int getReutersChannelId() {
        return reutersChannelId;
    }

    /**
     * Sets the value of the reutersChannelId property.
     * 
     */
    public void setReutersChannelId(int value) {
        this.reutersChannelId = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the registeredTimezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredTimezone() {
        return registeredTimezone;
    }

    /**
     * Sets the value of the registeredTimezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredTimezone(String value) {
        this.registeredTimezone = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the jobRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobRole() {
        return jobRole;
    }

    /**
     * Sets the value of the jobRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobRole(String value) {
        this.jobRole = value;
    }

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignId(String value) {
        this.campaignId = value;
    }

    /**
     * Gets the value of the currentTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTime() {
        return currentTime;
    }

    /**
     * Sets the value of the currentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTime(String value) {
        this.currentTime = value;
    }

    /**
     * Gets the value of the eulaAccepted property.
     * 
     */
    public boolean isEulaAccepted() {
        return eulaAccepted;
    }

    /**
     * Sets the value of the eulaAccepted property.
     * 
     */
    public void setEulaAccepted(boolean value) {
        this.eulaAccepted = value;
    }

    /**
     * Gets the value of the messagingDisabled property.
     * 
     */
    public boolean isMessagingDisabled() {
        return messagingDisabled;
    }

    /**
     * Sets the value of the messagingDisabled property.
     * 
     */
    public void setMessagingDisabled(boolean value) {
        this.messagingDisabled = value;
    }

    /**
     * Gets the value of the mobilizePlaylist property.
     * 
     */
    public boolean isMobilizePlaylist() {
        return mobilizePlaylist;
    }

    /**
     * Sets the value of the mobilizePlaylist property.
     * 
     */
    public void setMobilizePlaylist(boolean value) {
        this.mobilizePlaylist = value;
    }

    /**
     * Gets the value of the transcriptDisclaimerAccepted property.
     * 
     */
    public boolean isTranscriptDisclaimerAccepted() {
        return transcriptDisclaimerAccepted;
    }

    /**
     * Sets the value of the transcriptDisclaimerAccepted property.
     * 
     */
    public void setTranscriptDisclaimerAccepted(boolean value) {
        this.transcriptDisclaimerAccepted = value;
    }

    /**
     * Gets the value of the rememberToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRememberToken() {
        return rememberToken;
    }

    /**
     * Sets the value of the rememberToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRememberToken(String value) {
        this.rememberToken = value;
    }

    /**
     * Gets the value of the globalAdmin property.
     * 
     */
    public boolean isGlobalAdmin() {
        return globalAdmin;
    }

    /**
     * Sets the value of the globalAdmin property.
     * 
     */
    public void setGlobalAdmin(boolean value) {
        this.globalAdmin = value;
    }

    /**
     * Gets the value of the supportRoleLevel1 property.
     * 
     */
    public boolean isSupportRoleLevel1() {
        return supportRoleLevel1;
    }

    /**
     * Sets the value of the supportRoleLevel1 property.
     * 
     */
    public void setSupportRoleLevel1(boolean value) {
        this.supportRoleLevel1 = value;
    }

    /**
     * Gets the value of the supportRoleLevel2 property.
     * 
     */
    public boolean isSupportRoleLevel2() {
        return supportRoleLevel2;
    }

    /**
     * Sets the value of the supportRoleLevel2 property.
     * 
     */
    public void setSupportRoleLevel2(boolean value) {
        this.supportRoleLevel2 = value;
    }

    /**
     * Gets the value of the firstTimeVideo property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.FirstTimeVideo }
     *     
     */
    public Authentication.FirstTimeVideo getFirstTimeVideo() {
        return firstTimeVideo;
    }

    /**
     * Sets the value of the firstTimeVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.FirstTimeVideo }
     *     
     */
    public void setFirstTimeVideo(Authentication.FirstTimeVideo value) {
        this.firstTimeVideo = value;
    }

    /**
     * Gets the value of the lastLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastLogin() {
        return lastLogin;
    }

    /**
     * Sets the value of the lastLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastLogin(String value) {
        this.lastLogin = value;
    }

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserType(String value) {
        this.userType = value;
    }

    /**
     * Gets the value of the versions property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.Versions }
     *     
     */
    public Authentication.Versions getVersions() {
        return versions;
    }

    /**
     * Sets the value of the versions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.Versions }
     *     
     */
    public void setVersions(Authentication.Versions value) {
        this.versions = value;
    }

    /**
     * Gets the value of the channelMembership property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.ChannelMembership }
     *     
     */
    public Authentication.ChannelMembership getChannelMembership() {
        return channelMembership;
    }

    /**
     * Sets the value of the channelMembership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.ChannelMembership }
     *     
     */
    public void setChannelMembership(Authentication.ChannelMembership value) {
        this.channelMembership = value;
    }

    /**
     * Gets the value of the accessRights property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.AccessRights }
     *     
     */
    public Authentication.AccessRights getAccessRights() {
        return accessRights;
    }

    /**
     * Sets the value of the accessRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.AccessRights }
     *     
     */
    public void setAccessRights(Authentication.AccessRights value) {
        this.accessRights = value;
    }

    /**
     * Gets the value of the lowBandwidthStreams property.
     * 
     */
    public boolean isLowBandwidthStreams() {
        return lowBandwidthStreams;
    }

    /**
     * Sets the value of the lowBandwidthStreams property.
     * 
     */
    public void setLowBandwidthStreams(boolean value) {
        this.lowBandwidthStreams = value;
    }

    /**
     * Gets the value of the maxBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication.MaxBandwidth }
     *     
     */
    public Authentication.MaxBandwidth getMaxBandwidth() {
        return maxBandwidth;
    }

    /**
     * Sets the value of the maxBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication.MaxBandwidth }
     *     
     */
    public void setMaxBandwidth(Authentication.MaxBandwidth value) {
        this.maxBandwidth = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="desktop_studio" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "desktopStudio"
    })
    public static class AccessRights {

        @XmlElement(name = "desktop_studio")
        protected boolean desktopStudio;

        /**
         * Gets the value of the desktopStudio property.
         * 
         */
        public boolean isDesktopStudio() {
            return desktopStudio;
        }

        /**
         * Sets the value of the desktopStudio property.
         * 
         */
        public void setDesktopStudio(boolean value) {
            this.desktopStudio = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ckey2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ekey2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="expiration2" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ckey2",
        "ekey2",
        "expiration2"
    })
    public static class CacheKeys {

        @XmlElement(required = true)
        protected String ckey2;
        @XmlElement(required = true)
        protected String ekey2;
        protected int expiration2;

        /**
         * Gets the value of the ckey2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCkey2() {
            return ckey2;
        }

        /**
         * Sets the value of the ckey2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCkey2(String value) {
            this.ckey2 = value;
        }

        /**
         * Gets the value of the ekey2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEkey2() {
            return ekey2;
        }

        /**
         * Sets the value of the ekey2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEkey2(String value) {
            this.ekey2 = value;
        }

        /**
         * Gets the value of the expiration2 property.
         * 
         */
        public int getExpiration2() {
            return expiration2;
        }

        /**
         * Sets the value of the expiration2 property.
         * 
         */
        public void setExpiration2(int value) {
            this.expiration2 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="channel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="member" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "channel"
    })
    public static class ChannelMembership {

        protected List<Authentication.ChannelMembership.Channel> channel;
        @XmlAttribute
        protected Boolean all;

        /**
         * Gets the value of the channel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the channel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChannel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authentication.ChannelMembership.Channel }
         * 
         * 
         */
        public List<Authentication.ChannelMembership.Channel> getChannel() {
            if (channel == null) {
                channel = new ArrayList<Authentication.ChannelMembership.Channel>();
            }
            return this.channel;
        }

        /**
         * Gets the value of the all property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAll() {
            return all;
        }

        /**
         * Sets the value of the all property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAll(Boolean value) {
            this.all = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="member" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Channel {

            @XmlAttribute
            protected Integer id;
            @XmlAttribute
            protected Boolean member;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the member property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isMember() {
                return member;
            }

            /**
             * Sets the value of the member property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setMember(Boolean value) {
                this.member = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="channel_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FirstTimeVideo {

        @XmlAttribute
        protected String id;
        @XmlAttribute(name = "channel_id")
        protected String channelId;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the channelId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannelId() {
            return channelId;
        }

        /**
         * Sets the value of the channelId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannelId(String value) {
            this.channelId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bitrate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="bandwidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bitrate",
        "bandwidth"
    })
    public static class MaxBandwidth {

        protected int bitrate;
        @XmlElement(required = true)
        protected String bandwidth;

        /**
         * Gets the value of the bitrate property.
         * 
         */
        public int getBitrate() {
            return bitrate;
        }

        /**
         * Sets the value of the bitrate property.
         * 
         */
        public void setBitrate(int value) {
            this.bitrate = value;
        }

        /**
         * Gets the value of the bandwidth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBandwidth() {
            return bandwidth;
        }

        /**
         * Sets the value of the bandwidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBandwidth(String value) {
            this.bandwidth = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version"
    })
    public static class Versions {

        @XmlElement(required = true)
        protected List<Authentication.Versions.Version> version;

        /**
         * Gets the value of the version property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the version property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authentication.Versions.Version }
         * 
         * 
         */
        public List<Authentication.Versions.Version> getVersion() {
            if (version == null) {
                version = new ArrayList<Authentication.Versions.Version>();
            }
            return this.version;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Version {

            @XmlAttribute
            protected String key;
            @XmlAttribute
            protected String value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
