//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:11:10 PM EEST 
//


package com.epam.triimob.netbiscuits.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paging_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paging_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemscount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pagescount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="per_page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paging_info", propOrder = {
    "itemscount",
    "pagescount",
    "page",
    "perPage"
})
public class PagingInfo {

    protected int itemscount;
    protected int pagescount;
    protected int page;
    @XmlElement(name = "per_page")
    protected int perPage;

    /**
     * Gets the value of the itemscount property.
     * 
     */
    public int getItemscount() {
        return itemscount;
    }

    /**
     * Sets the value of the itemscount property.
     * 
     */
    public void setItemscount(int value) {
        this.itemscount = value;
    }

    /**
     * Gets the value of the pagescount property.
     * 
     */
    public int getPagescount() {
        return pagescount;
    }

    /**
     * Sets the value of the pagescount property.
     * 
     */
    public void setPagescount(int value) {
        this.pagescount = value;
    }

    /**
     * Gets the value of the page property.
     * 
     */
    public int getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     */
    public void setPage(int value) {
        this.page = value;
    }

    /**
     * Gets the value of the perPage property.
     * 
     */
    public int getPerPage() {
        return perPage;
    }

    /**
     * Sets the value of the perPage property.
     * 
     */
    public void setPerPage(int value) {
        this.perPage = value;
    }

}
