//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:11:10 PM EEST 
//


package com.epam.triimob.netbiscuits.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="authentication" type="{}authentication"/>
 *                   &lt;element name="paging_info" type="{}paging_info"/>
 *                   &lt;element name="system_logos" type="{}system_logos"/>
 *                   &lt;element name="tagged_items" type="{}tagged_items"/>
 *                   &lt;sequence>
 *                     &lt;element name="search_stats">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="hits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="total_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="scheduled_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="ondemand_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="max_rank" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="search_criteria" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="fquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="similar_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="clipscount">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="pagescount">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="clips">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="clip" type="{}show" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="navigation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;element name="transcript_verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="transcript">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="tokens">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="token" type="{}transcript" maxOccurs="unbounded"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="passages">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="passage" maxOccurs="unbounded">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="topics">
 *                                                     &lt;complexType>
 *                                                       &lt;complexContent>
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                           &lt;sequence>
 *                                                             &lt;element name="topic">
 *                                                               &lt;complexType>
 *                                                                 &lt;complexContent>
 *                                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                     &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                                                   &lt;/restriction>
 *                                                                 &lt;/complexContent>
 *                                                               &lt;/complexType>
 *                                                             &lt;/element>
 *                                                           &lt;/sequence>
 *                                                         &lt;/restriction>
 *                                                       &lt;/complexContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                   &lt;element name="keywords">
 *                                                     &lt;complexType>
 *                                                       &lt;complexContent>
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                           &lt;sequence>
 *                                                             &lt;element name="keyword" maxOccurs="unbounded">
 *                                                               &lt;complexType>
 *                                                                 &lt;complexContent>
 *                                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                     &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                                                   &lt;/restriction>
 *                                                                 &lt;/complexContent>
 *                                                               &lt;/complexType>
 *                                                             &lt;/element>
 *                                                           &lt;/sequence>
 *                                                         &lt;/restriction>
 *                                                       &lt;/complexContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                 &lt;/sequence>
 *                                                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                 &lt;attribute name="start_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                 &lt;attribute name="end_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "data"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected Response.Result result;
    @XmlElement(required = true)
    protected Response.Data data;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Result }
     *     
     */
    public Response.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Result }
     *     
     */
    public void setResult(Response.Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Data }
     *     
     */
    public Response.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Data }
     *     
     */
    public void setData(Response.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="authentication" type="{}authentication"/>
     *         &lt;element name="paging_info" type="{}paging_info"/>
     *         &lt;element name="system_logos" type="{}system_logos"/>
     *         &lt;element name="tagged_items" type="{}tagged_items"/>
     *         &lt;sequence>
     *           &lt;element name="search_stats">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="hits" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="total_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="scheduled_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="ondemand_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="max_rank" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="search_criteria" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="fquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="similar_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="clipscount">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="pagescount">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                   &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="clips">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="clip" type="{}show" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="navigation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;element name="transcript_verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *           &lt;element name="transcript">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="tokens">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="token" type="{}transcript" maxOccurs="unbounded"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="passages">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="passage" maxOccurs="unbounded">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="topics">
     *                                           &lt;complexType>
     *                                             &lt;complexContent>
     *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                 &lt;sequence>
     *                                                   &lt;element name="topic">
     *                                                     &lt;complexType>
     *                                                       &lt;complexContent>
     *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                           &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                                                         &lt;/restriction>
     *                                                       &lt;/complexContent>
     *                                                     &lt;/complexType>
     *                                                   &lt;/element>
     *                                                 &lt;/sequence>
     *                                               &lt;/restriction>
     *                                             &lt;/complexContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                         &lt;element name="keywords">
     *                                           &lt;complexType>
     *                                             &lt;complexContent>
     *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                 &lt;sequence>
     *                                                   &lt;element name="keyword" maxOccurs="unbounded">
     *                                                     &lt;complexType>
     *                                                       &lt;complexContent>
     *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                           &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                                                         &lt;/restriction>
     *                                                       &lt;/complexContent>
     *                                                     &lt;/complexType>
     *                                                   &lt;/element>
     *                                                 &lt;/sequence>
     *                                               &lt;/restriction>
     *                                             &lt;/complexContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                       &lt;/sequence>
     *                                       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                       &lt;attribute name="start_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                       &lt;attribute name="end_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authentication",
        "pagingInfo",
        "systemLogos",
        "taggedItems",
        "searchStats",
        "searchCriteria",
        "fquery",
        "similarTo",
        "clipscount",
        "pagescount",
        "clips",
        "navigation",
        "transcriptVerified",
        "transcript"
    })
    public static class Data {

        protected Authentication authentication;
        @XmlElement(name = "paging_info")
        protected PagingInfo pagingInfo;
        @XmlElement(name = "system_logos")
        protected SystemLogos systemLogos;
        @XmlElement(name = "tagged_items")
        protected TaggedItems taggedItems;
        @XmlElement(name = "search_stats")
        protected Response.Data.SearchStats searchStats;
        @XmlElement(name = "search_criteria")
        protected String searchCriteria;
        protected String fquery;
        @XmlElement(name = "similar_to")
        protected String similarTo;
        protected Response.Data.Clipscount clipscount;
        protected Response.Data.Pagescount pagescount;
        protected Response.Data.Clips clips;
        protected String navigation;
        @XmlElement(name = "transcript_verified")
        protected Boolean transcriptVerified;
        protected Response.Data.Transcript transcript;

        /**
         * Gets the value of the authentication property.
         * 
         * @return
         *     possible object is
         *     {@link Authentication }
         *     
         */
        public Authentication getAuthentication() {
            return authentication;
        }

        /**
         * Sets the value of the authentication property.
         * 
         * @param value
         *     allowed object is
         *     {@link Authentication }
         *     
         */
        public void setAuthentication(Authentication value) {
            this.authentication = value;
        }

        /**
         * Gets the value of the pagingInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PagingInfo }
         *     
         */
        public PagingInfo getPagingInfo() {
            return pagingInfo;
        }

        /**
         * Sets the value of the pagingInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PagingInfo }
         *     
         */
        public void setPagingInfo(PagingInfo value) {
            this.pagingInfo = value;
        }

        /**
         * Gets the value of the systemLogos property.
         * 
         * @return
         *     possible object is
         *     {@link SystemLogos }
         *     
         */
        public SystemLogos getSystemLogos() {
            return systemLogos;
        }

        /**
         * Sets the value of the systemLogos property.
         * 
         * @param value
         *     allowed object is
         *     {@link SystemLogos }
         *     
         */
        public void setSystemLogos(SystemLogos value) {
            this.systemLogos = value;
        }

        /**
         * Gets the value of the taggedItems property.
         * 
         * @return
         *     possible object is
         *     {@link TaggedItems }
         *     
         */
        public TaggedItems getTaggedItems() {
            return taggedItems;
        }

        /**
         * Sets the value of the taggedItems property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaggedItems }
         *     
         */
        public void setTaggedItems(TaggedItems value) {
            this.taggedItems = value;
        }

        /**
         * Gets the value of the searchStats property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.SearchStats }
         *     
         */
        public Response.Data.SearchStats getSearchStats() {
            return searchStats;
        }

        /**
         * Sets the value of the searchStats property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.SearchStats }
         *     
         */
        public void setSearchStats(Response.Data.SearchStats value) {
            this.searchStats = value;
        }

        /**
         * Gets the value of the searchCriteria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchCriteria() {
            return searchCriteria;
        }

        /**
         * Sets the value of the searchCriteria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchCriteria(String value) {
            this.searchCriteria = value;
        }

        /**
         * Gets the value of the fquery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFquery() {
            return fquery;
        }

        /**
         * Sets the value of the fquery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFquery(String value) {
            this.fquery = value;
        }

        /**
         * Gets the value of the similarTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSimilarTo() {
            return similarTo;
        }

        /**
         * Sets the value of the similarTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSimilarTo(String value) {
            this.similarTo = value;
        }

        /**
         * Gets the value of the clipscount property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.Clipscount }
         *     
         */
        public Response.Data.Clipscount getClipscount() {
            return clipscount;
        }

        /**
         * Sets the value of the clipscount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.Clipscount }
         *     
         */
        public void setClipscount(Response.Data.Clipscount value) {
            this.clipscount = value;
        }

        /**
         * Gets the value of the pagescount property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.Pagescount }
         *     
         */
        public Response.Data.Pagescount getPagescount() {
            return pagescount;
        }

        /**
         * Sets the value of the pagescount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.Pagescount }
         *     
         */
        public void setPagescount(Response.Data.Pagescount value) {
            this.pagescount = value;
        }

        /**
         * Gets the value of the clips property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.Clips }
         *     
         */
        public Response.Data.Clips getClips() {
            return clips;
        }

        /**
         * Sets the value of the clips property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.Clips }
         *     
         */
        public void setClips(Response.Data.Clips value) {
            this.clips = value;
        }

        /**
         * Gets the value of the navigation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNavigation() {
            return navigation;
        }

        /**
         * Sets the value of the navigation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNavigation(String value) {
            this.navigation = value;
        }

        /**
         * Gets the value of the transcriptVerified property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isTranscriptVerified() {
            return transcriptVerified;
        }

        /**
         * Sets the value of the transcriptVerified property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setTranscriptVerified(Boolean value) {
            this.transcriptVerified = value;
        }

        /**
         * Gets the value of the transcript property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.Transcript }
         *     
         */
        public Response.Data.Transcript getTranscript() {
            return transcript;
        }

        /**
         * Sets the value of the transcript property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.Transcript }
         *     
         */
        public void setTranscript(Response.Data.Transcript value) {
            this.transcript = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="clip" type="{}show" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clip"
        })
        public static class Clips {

            @XmlElement(required = true)
            protected List<Show> clip;

            /**
             * Gets the value of the clip property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clip property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClip().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Show }
             * 
             * 
             */
            public List<Show> getClip() {
                if (clip == null) {
                    clip = new ArrayList<Show>();
                }
                return this.clip;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Clipscount {

            @XmlAttribute(name = "on_demand")
            protected Integer onDemand;
            @XmlAttribute
            protected Integer scheduled;
            @XmlAttribute
            protected Integer total;

            /**
             * Gets the value of the onDemand property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOnDemand() {
                return onDemand;
            }

            /**
             * Sets the value of the onDemand property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOnDemand(Integer value) {
                this.onDemand = value;
            }

            /**
             * Gets the value of the scheduled property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getScheduled() {
                return scheduled;
            }

            /**
             * Sets the value of the scheduled property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setScheduled(Integer value) {
                this.scheduled = value;
            }

            /**
             * Gets the value of the total property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotal(Integer value) {
                this.total = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="on_demand" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Pagescount {

            @XmlAttribute(name = "on_demand")
            protected Integer onDemand;
            @XmlAttribute
            protected Integer scheduled;
            @XmlAttribute
            protected Integer total;

            /**
             * Gets the value of the onDemand property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOnDemand() {
                return onDemand;
            }

            /**
             * Sets the value of the onDemand property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOnDemand(Integer value) {
                this.onDemand = value;
            }

            /**
             * Gets the value of the scheduled property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getScheduled() {
                return scheduled;
            }

            /**
             * Sets the value of the scheduled property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setScheduled(Integer value) {
                this.scheduled = value;
            }

            /**
             * Gets the value of the total property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotal(Integer value) {
                this.total = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="hits" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="total_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="scheduled_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ondemand_hits" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="max_rank" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SearchStats {

            @XmlAttribute
            protected Integer hits;
            @XmlAttribute(name = "total_hits")
            protected Integer totalHits;
            @XmlAttribute(name = "scheduled_hits")
            protected Integer scheduledHits;
            @XmlAttribute(name = "ondemand_hits")
            protected Integer ondemandHits;
            @XmlAttribute(name = "max_rank")
            protected Integer maxRank;

            /**
             * Gets the value of the hits property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHits() {
                return hits;
            }

            /**
             * Sets the value of the hits property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHits(Integer value) {
                this.hits = value;
            }

            /**
             * Gets the value of the totalHits property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalHits() {
                return totalHits;
            }

            /**
             * Sets the value of the totalHits property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalHits(Integer value) {
                this.totalHits = value;
            }

            /**
             * Gets the value of the scheduledHits property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getScheduledHits() {
                return scheduledHits;
            }

            /**
             * Sets the value of the scheduledHits property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setScheduledHits(Integer value) {
                this.scheduledHits = value;
            }

            /**
             * Gets the value of the ondemandHits property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOndemandHits() {
                return ondemandHits;
            }

            /**
             * Sets the value of the ondemandHits property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOndemandHits(Integer value) {
                this.ondemandHits = value;
            }

            /**
             * Gets the value of the maxRank property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMaxRank() {
                return maxRank;
            }

            /**
             * Sets the value of the maxRank property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMaxRank(Integer value) {
                this.maxRank = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tokens">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="token" type="{}transcript" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="passages">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="passage" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="topics">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="topic">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                               &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="keywords">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="keyword" maxOccurs="unbounded">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                               &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="start_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="end_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tokens",
            "passages"
        })
        public static class Transcript {

            @XmlElement(required = true)
            protected Response.Data.Transcript.Tokens tokens;
            @XmlElement(required = true)
            protected Response.Data.Transcript.Passages passages;

            /**
             * Gets the value of the tokens property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Data.Transcript.Tokens }
             *     
             */
            public Response.Data.Transcript.Tokens getTokens() {
                return tokens;
            }

            /**
             * Sets the value of the tokens property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Data.Transcript.Tokens }
             *     
             */
            public void setTokens(Response.Data.Transcript.Tokens value) {
                this.tokens = value;
            }

            /**
             * Gets the value of the passages property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Data.Transcript.Passages }
             *     
             */
            public Response.Data.Transcript.Passages getPassages() {
                return passages;
            }

            /**
             * Sets the value of the passages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Data.Transcript.Passages }
             *     
             */
            public void setPassages(Response.Data.Transcript.Passages value) {
                this.passages = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="passage" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="topics">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="topic">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                     &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="keywords">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="keyword" maxOccurs="unbounded">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                     &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="start_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="end_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "passage"
            })
            public static class Passages {

                @XmlElement(required = true)
                protected List<Response.Data.Transcript.Passages.Passage> passage;

                /**
                 * Gets the value of the passage property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the passage property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPassage().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Response.Data.Transcript.Passages.Passage }
                 * 
                 * 
                 */
                public List<Response.Data.Transcript.Passages.Passage> getPassage() {
                    if (passage == null) {
                        passage = new ArrayList<Response.Data.Transcript.Passages.Passage>();
                    }
                    return this.passage;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="topics">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="topic">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                           &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="keywords">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="keyword" maxOccurs="unbounded">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                           &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="start_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="end_idref" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "topics",
                    "keywords"
                })
                public static class Passage {

                    @XmlElement(required = true)
                    protected Response.Data.Transcript.Passages.Passage.Topics topics;
                    @XmlElement(required = true)
                    protected Response.Data.Transcript.Passages.Passage.Keywords keywords;
                    @XmlAttribute
                    protected Integer id;
                    @XmlAttribute(name = "start_idref")
                    protected Integer startIdref;
                    @XmlAttribute(name = "end_idref")
                    protected Integer endIdref;

                    /**
                     * Gets the value of the topics property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Response.Data.Transcript.Passages.Passage.Topics }
                     *     
                     */
                    public Response.Data.Transcript.Passages.Passage.Topics getTopics() {
                        return topics;
                    }

                    /**
                     * Sets the value of the topics property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Response.Data.Transcript.Passages.Passage.Topics }
                     *     
                     */
                    public void setTopics(Response.Data.Transcript.Passages.Passage.Topics value) {
                        this.topics = value;
                    }

                    /**
                     * Gets the value of the keywords property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Response.Data.Transcript.Passages.Passage.Keywords }
                     *     
                     */
                    public Response.Data.Transcript.Passages.Passage.Keywords getKeywords() {
                        return keywords;
                    }

                    /**
                     * Sets the value of the keywords property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Response.Data.Transcript.Passages.Passage.Keywords }
                     *     
                     */
                    public void setKeywords(Response.Data.Transcript.Passages.Passage.Keywords value) {
                        this.keywords = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setId(Integer value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the startIdref property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getStartIdref() {
                        return startIdref;
                    }

                    /**
                     * Sets the value of the startIdref property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setStartIdref(Integer value) {
                        this.startIdref = value;
                    }

                    /**
                     * Gets the value of the endIdref property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getEndIdref() {
                        return endIdref;
                    }

                    /**
                     * Sets the value of the endIdref property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setEndIdref(Integer value) {
                        this.endIdref = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="keyword" maxOccurs="unbounded">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *                 &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "keyword"
                    })
                    public static class Keywords {

                        @XmlElement(required = true)
                        protected List<Response.Data.Transcript.Passages.Passage.Keywords.Keyword> keyword;

                        /**
                         * Gets the value of the keyword property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the keyword property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getKeyword().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Response.Data.Transcript.Passages.Passage.Keywords.Keyword }
                         * 
                         * 
                         */
                        public List<Response.Data.Transcript.Passages.Passage.Keywords.Keyword> getKeyword() {
                            if (keyword == null) {
                                keyword = new ArrayList<Response.Data.Transcript.Passages.Passage.Keywords.Keyword>();
                            }
                            return this.keyword;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *       &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "")
                        public static class Keyword {

                            @XmlAttribute
                            protected String text;
                            @XmlAttribute
                            protected BigDecimal score;

                            /**
                             * Gets the value of the text property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getText() {
                                return text;
                            }

                            /**
                             * Sets the value of the text property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setText(String value) {
                                this.text = value;
                            }

                            /**
                             * Gets the value of the score property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link BigDecimal }
                             *     
                             */
                            public BigDecimal getScore() {
                                return score;
                            }

                            /**
                             * Sets the value of the score property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link BigDecimal }
                             *     
                             */
                            public void setScore(BigDecimal value) {
                                this.score = value;
                            }

                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="topic">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *                 &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "topic"
                    })
                    public static class Topics {

                        @XmlElement(required = true)
                        protected Response.Data.Transcript.Passages.Passage.Topics.Topic topic;

                        /**
                         * Gets the value of the topic property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Response.Data.Transcript.Passages.Passage.Topics.Topic }
                         *     
                         */
                        public Response.Data.Transcript.Passages.Passage.Topics.Topic getTopic() {
                            return topic;
                        }

                        /**
                         * Sets the value of the topic property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Response.Data.Transcript.Passages.Passage.Topics.Topic }
                         *     
                         */
                        public void setTopic(Response.Data.Transcript.Passages.Passage.Topics.Topic value) {
                            this.topic = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *       &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}decimal" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "")
                        public static class Topic {

                            @XmlAttribute
                            protected String text;
                            @XmlAttribute
                            protected BigDecimal score;

                            /**
                             * Gets the value of the text property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getText() {
                                return text;
                            }

                            /**
                             * Sets the value of the text property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setText(String value) {
                                this.text = value;
                            }

                            /**
                             * Gets the value of the score property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link BigDecimal }
                             *     
                             */
                            public BigDecimal getScore() {
                                return score;
                            }

                            /**
                             * Sets the value of the score property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link BigDecimal }
                             *     
                             */
                            public void setScore(BigDecimal value) {
                                this.score = value;
                            }

                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="token" type="{}transcript" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "token"
            })
            public static class Tokens {

                @XmlElement(required = true)
                protected List<Transcript> token;

                /**
                 * Gets the value of the token property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the token property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getToken().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link com.epam.triimob.netbiscuits.xml.trimob.rest.domain.Transcript }
                 * 
                 * 
                 */
                public List<Transcript> getToken() {
                    if (token == null) {
                        token = new ArrayList<Transcript>();
                    }
                    return this.token;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "message",
        "timezone",
        "domain"
    })
    public static class Result {

        @XmlElement(required = true)
        protected String status;
        protected String message;
        protected String timezone;
        protected String domain;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

        /**
         * Gets the value of the timezone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimezone() {
            return timezone;
        }

        /**
         * Sets the value of the timezone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimezone(String value) {
            this.timezone = value;
        }

        /**
         * Gets the value of the domain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDomain() {
            return domain;
        }

        /**
         * Sets the value of the domain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDomain(String value) {
            this.domain = value;
        }

    }

}
