//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 12:23:44 AM EET 
//


package com.epam.triimob.netbiscuits.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channel_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="show_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="includes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="term" type="{}term" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="excludes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requires" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="after_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="before_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mode",
    "order",
    "channelId",
    "showId",
    "includes",
    "excludes",
    "requires",
    "afterDate",
    "beforeDate"
})
@XmlRootElement(name = "search_criteria")
public class SearchCriteria {

    @XmlElement(required = true)
    protected String mode;
    @XmlElement(required = true)
    protected String order;
    @XmlElement(name = "channel_id", required = true)
    protected String channelId;
    @XmlElement(name = "show_id", required = true)
    protected String showId;
    @XmlElement(required = true)
    protected SearchCriteria.Includes includes;
    @XmlElement(required = true)
    protected String excludes;
    @XmlElement(required = true)
    protected String requires;
    @XmlElement(name = "after_date", required = true)
    protected String afterDate;
    @XmlElement(name = "before_date", required = true)
    protected String beforeDate;

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrder(String value) {
        this.order = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelId(String value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the showId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowId() {
        return showId;
    }

    /**
     * Sets the value of the showId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowId(String value) {
        this.showId = value;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link SearchCriteria.Includes }
     *     
     */
    public SearchCriteria.Includes getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchCriteria.Includes }
     *     
     */
    public void setIncludes(SearchCriteria.Includes value) {
        this.includes = value;
    }

    /**
     * Gets the value of the excludes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludes() {
        return excludes;
    }

    /**
     * Sets the value of the excludes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludes(String value) {
        this.excludes = value;
    }

    /**
     * Gets the value of the requires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequires() {
        return requires;
    }

    /**
     * Sets the value of the requires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequires(String value) {
        this.requires = value;
    }

    /**
     * Gets the value of the afterDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterDate() {
        return afterDate;
    }

    /**
     * Sets the value of the afterDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterDate(String value) {
        this.afterDate = value;
    }

    /**
     * Gets the value of the beforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeDate() {
        return beforeDate;
    }

    /**
     * Sets the value of the beforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeDate(String value) {
        this.beforeDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="term" type="{}term" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "term"
    })
    public static class Includes {

        @XmlElement(required = true)
        protected List<Term> term;

        /**
         * Gets the value of the term property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the term property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTerm().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Term }
         * 
         * 
         */
        public List<Term> getTerm() {
            if (term == null) {
                term = new ArrayList<Term>();
            }
            return this.term;
        }

    }

}
