//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:11:10 PM EEST 
//


package com.epam.triimob.netbiscuits.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for show complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="show">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="embargo" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="live_status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="production_room_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quote2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="restricted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="comment_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="has_transcript" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="stream_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="http_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="share_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="share_link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custom_thumb" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="thumb_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thumbnails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="thumbnail" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="streams" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="live_stream_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stream_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stream_url_low" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="production_room" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="publish_point_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="production_channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="source" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="teasers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="highlights" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hit" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rank" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="live" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="production_status_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="brand_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="stream_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publish_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="has_recording" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="has_mobile" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="group_channel_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="company_channel_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="use_generated_thumbnail" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="disable_comments" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "show", propOrder = {
    "name",
    "title",
    "embargo",
    "liveStatus",
    "productionRoomId",
    "description",
    "quote",
    "quote2",
    "attribution",
    "keywords",
    "restricted",
    "startTime",
    "endTime",
    "duration",
    "status",
    "commentCount",
    "hasTranscript",
    "streamUrl",
    "httpUrl",
    "owner",
    "shareToken",
    "shareLink",
    "terms",
    "customThumb",
    "thumbUrl",
    "thumbnails",
    "streams",
    "liveStreamInfo",
    "sources",
    "teasers",
    "highlights"
})
public class Show {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String title;
    protected boolean embargo;
    @XmlElement(name = "live_status")
    protected int liveStatus;
    @XmlElement(name = "production_room_id")
    protected int productionRoomId;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String quote;
    @XmlElement(required = true)
    protected String quote2;
    @XmlElement(required = true)
    protected String attribution;
    @XmlElement(required = true)
    protected String keywords;
    protected boolean restricted;
    @XmlElement(name = "start_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "end_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    protected int duration;
    protected int status;
    @XmlElement(name = "comment_count")
    protected int commentCount;
    @XmlElement(name = "has_transcript")
    protected boolean hasTranscript;
    @XmlElement(name = "stream_url", required = true)
    protected String streamUrl;
    @XmlElement(name = "http_url", required = true)
    protected String httpUrl;
    @XmlElement(required = true)
    protected String owner;
    @XmlElement(name = "share_token", required = true)
    protected String shareToken;
    @XmlElement(name = "share_link", required = true)
    protected String shareLink;
    @XmlElement(required = true)
    protected String terms;
    @XmlElement(name = "custom_thumb")
    protected boolean customThumb;
    @XmlElement(name = "thumb_url", required = true)
    protected String thumbUrl;
    @XmlElement(required = true)
    protected Show.Thumbnails thumbnails;
    @XmlElement(required = true)
    protected String streams;
    @XmlElement(name = "live_stream_info", required = true)
    protected Show.LiveStreamInfo liveStreamInfo;
    @XmlElement(required = true)
    protected Show.Sources sources;
    @XmlElement(required = true)
    protected String teasers;
    @XmlElement(required = true)
    protected String highlights;
    @XmlAttribute
    protected Integer hit;
    @XmlAttribute
    protected Integer rank;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected Boolean live;
    @XmlAttribute(name = "production_status_id")
    protected Integer productionStatusId;
    @XmlAttribute(name = "brand_id")
    protected Integer brandId;
    @XmlAttribute(name = "stream_type")
    protected String streamType;
    @XmlAttribute(name = "publish_date")
    protected String publishDate;
    @XmlAttribute(name = "created_at")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdAt;
    @XmlAttribute(name = "updated_at")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedAt;
    @XmlAttribute
    protected String user;
    @XmlAttribute
    protected String visibility;
    @XmlAttribute(name = "has_recording")
    protected Integer hasRecording;
    @XmlAttribute(name = "has_mobile")
    protected Integer hasMobile;
    @XmlAttribute(name = "group_channel_id")
    protected Integer groupChannelId;
    @XmlAttribute(name = "company_channel_id")
    protected Integer companyChannelId;
    @XmlAttribute(name = "use_generated_thumbnail")
    protected Boolean useGeneratedThumbnail;
    @XmlAttribute(name = "disable_comments")
    protected Boolean disableComments;
    @XmlAttribute
    protected Integer version;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the embargo property.
     * 
     */
    public boolean isEmbargo() {
        return embargo;
    }

    /**
     * Sets the value of the embargo property.
     * 
     */
    public void setEmbargo(boolean value) {
        this.embargo = value;
    }

    /**
     * Gets the value of the liveStatus property.
     * 
     */
    public int getLiveStatus() {
        return liveStatus;
    }

    /**
     * Sets the value of the liveStatus property.
     * 
     */
    public void setLiveStatus(int value) {
        this.liveStatus = value;
    }

    /**
     * Gets the value of the productionRoomId property.
     * 
     */
    public int getProductionRoomId() {
        return productionRoomId;
    }

    /**
     * Sets the value of the productionRoomId property.
     * 
     */
    public void setProductionRoomId(int value) {
        this.productionRoomId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the quote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuote() {
        return quote;
    }

    /**
     * Sets the value of the quote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuote(String value) {
        this.quote = value;
    }

    /**
     * Gets the value of the quote2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuote2() {
        return quote2;
    }

    /**
     * Sets the value of the quote2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuote2(String value) {
        this.quote2 = value;
    }

    /**
     * Gets the value of the attribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * Sets the value of the attribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribution(String value) {
        this.attribution = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywords(String value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the restricted property.
     * 
     */
    public boolean isRestricted() {
        return restricted;
    }

    /**
     * Sets the value of the restricted property.
     * 
     */
    public void setRestricted(boolean value) {
        this.restricted = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(int value) {
        this.duration = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the commentCount property.
     * 
     */
    public int getCommentCount() {
        return commentCount;
    }

    /**
     * Sets the value of the commentCount property.
     * 
     */
    public void setCommentCount(int value) {
        this.commentCount = value;
    }

    /**
     * Gets the value of the hasTranscript property.
     * 
     */
    public boolean isHasTranscript() {
        return hasTranscript;
    }

    /**
     * Sets the value of the hasTranscript property.
     * 
     */
    public void setHasTranscript(boolean value) {
        this.hasTranscript = value;
    }

    /**
     * Gets the value of the streamUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamUrl() {
        return streamUrl;
    }

    /**
     * Sets the value of the streamUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamUrl(String value) {
        this.streamUrl = value;
    }

    /**
     * Gets the value of the httpUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpUrl() {
        return httpUrl;
    }

    /**
     * Sets the value of the httpUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpUrl(String value) {
        this.httpUrl = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the shareToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareToken() {
        return shareToken;
    }

    /**
     * Sets the value of the shareToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareToken(String value) {
        this.shareToken = value;
    }

    /**
     * Gets the value of the shareLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareLink() {
        return shareLink;
    }

    /**
     * Sets the value of the shareLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareLink(String value) {
        this.shareLink = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerms(String value) {
        this.terms = value;
    }

    /**
     * Gets the value of the customThumb property.
     * 
     */
    public boolean isCustomThumb() {
        return customThumb;
    }

    /**
     * Sets the value of the customThumb property.
     * 
     */
    public void setCustomThumb(boolean value) {
        this.customThumb = value;
    }

    /**
     * Gets the value of the thumbUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbUrl() {
        return thumbUrl;
    }

    /**
     * Sets the value of the thumbUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbUrl(String value) {
        this.thumbUrl = value;
    }

    /**
     * Gets the value of the thumbnails property.
     * 
     * @return
     *     possible object is
     *     {@link Show.Thumbnails }
     *     
     */
    public Show.Thumbnails getThumbnails() {
        return thumbnails;
    }

    /**
     * Sets the value of the thumbnails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Show.Thumbnails }
     *     
     */
    public void setThumbnails(Show.Thumbnails value) {
        this.thumbnails = value;
    }

    /**
     * Gets the value of the streams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreams() {
        return streams;
    }

    /**
     * Sets the value of the streams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreams(String value) {
        this.streams = value;
    }

    /**
     * Gets the value of the liveStreamInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Show.LiveStreamInfo }
     *     
     */
    public Show.LiveStreamInfo getLiveStreamInfo() {
        return liveStreamInfo;
    }

    /**
     * Sets the value of the liveStreamInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Show.LiveStreamInfo }
     *     
     */
    public void setLiveStreamInfo(Show.LiveStreamInfo value) {
        this.liveStreamInfo = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Show.Sources }
     *     
     */
    public Show.Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Show.Sources }
     *     
     */
    public void setSources(Show.Sources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the teasers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeasers() {
        return teasers;
    }

    /**
     * Sets the value of the teasers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeasers(String value) {
        this.teasers = value;
    }

    /**
     * Gets the value of the highlights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighlights() {
        return highlights;
    }

    /**
     * Sets the value of the highlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighlights(String value) {
        this.highlights = value;
    }

    /**
     * Gets the value of the hit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHit() {
        return hit;
    }

    /**
     * Sets the value of the hit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHit(Integer value) {
        this.hit = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRank(Integer value) {
        this.rank = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the live property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLive() {
        return live;
    }

    /**
     * Sets the value of the live property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLive(Boolean value) {
        this.live = value;
    }

    /**
     * Gets the value of the productionStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductionStatusId() {
        return productionStatusId;
    }

    /**
     * Sets the value of the productionStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductionStatusId(Integer value) {
        this.productionStatusId = value;
    }

    /**
     * Gets the value of the brandId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * Sets the value of the brandId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrandId(Integer value) {
        this.brandId = value;
    }

    /**
     * Gets the value of the streamType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamType() {
        return streamType;
    }

    /**
     * Sets the value of the streamType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamType(String value) {
        this.streamType = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishDate(String value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedAt(XMLGregorianCalendar value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the updatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the value of the updatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedAt(XMLGregorianCalendar value) {
        this.updatedAt = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the hasRecording property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHasRecording() {
        return hasRecording;
    }

    /**
     * Sets the value of the hasRecording property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHasRecording(Integer value) {
        this.hasRecording = value;
    }

    /**
     * Gets the value of the hasMobile property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHasMobile() {
        return hasMobile;
    }

    /**
     * Sets the value of the hasMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHasMobile(Integer value) {
        this.hasMobile = value;
    }

    /**
     * Gets the value of the groupChannelId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupChannelId() {
        return groupChannelId;
    }

    /**
     * Sets the value of the groupChannelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupChannelId(Integer value) {
        this.groupChannelId = value;
    }

    /**
     * Gets the value of the companyChannelId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompanyChannelId() {
        return companyChannelId;
    }

    /**
     * Sets the value of the companyChannelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompanyChannelId(Integer value) {
        this.companyChannelId = value;
    }

    /**
     * Gets the value of the useGeneratedThumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseGeneratedThumbnail() {
        return useGeneratedThumbnail;
    }

    /**
     * Sets the value of the useGeneratedThumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseGeneratedThumbnail(Boolean value) {
        this.useGeneratedThumbnail = value;
    }

    /**
     * Gets the value of the disableComments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisableComments() {
        return disableComments;
    }

    /**
     * Sets the value of the disableComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisableComments(Boolean value) {
        this.disableComments = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stream_url_low" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="production_room" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="publish_point_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="production_channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "streamUrl",
        "streamUrlLow",
        "productionRoom",
        "publishPointId",
        "productionChannel"
    })
    public static class LiveStreamInfo {

        @XmlElement(name = "stream_url", required = true)
        protected String streamUrl;
        @XmlElement(name = "stream_url_low", required = true)
        protected String streamUrlLow;
        @XmlElement(name = "production_room", required = true)
        protected String productionRoom;
        @XmlElement(name = "publish_point_id")
        protected int publishPointId;
        @XmlElement(name = "production_channel", required = true)
        protected String productionChannel;
        @XmlAttribute
        protected String source;

        /**
         * Gets the value of the streamUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreamUrl() {
            return streamUrl;
        }

        /**
         * Sets the value of the streamUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreamUrl(String value) {
            this.streamUrl = value;
        }

        /**
         * Gets the value of the streamUrlLow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreamUrlLow() {
            return streamUrlLow;
        }

        /**
         * Sets the value of the streamUrlLow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreamUrlLow(String value) {
            this.streamUrlLow = value;
        }

        /**
         * Gets the value of the productionRoom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductionRoom() {
            return productionRoom;
        }

        /**
         * Sets the value of the productionRoom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductionRoom(String value) {
            this.productionRoom = value;
        }

        /**
         * Gets the value of the publishPointId property.
         * 
         */
        public int getPublishPointId() {
            return publishPointId;
        }

        /**
         * Sets the value of the publishPointId property.
         * 
         */
        public void setPublishPointId(int value) {
            this.publishPointId = value;
        }

        /**
         * Gets the value of the productionChannel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductionChannel() {
            return productionChannel;
        }

        /**
         * Sets the value of the productionChannel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductionChannel(String value) {
            this.productionChannel = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="source" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source"
    })
    public static class Sources {

        @XmlElement(required = true)
        protected List<Show.Sources.Source> source;

        /**
         * Gets the value of the source property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the source property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Show.Sources.Source }
         * 
         * 
         */
        public List<Show.Sources.Source> getSource() {
            if (source == null) {
                source = new ArrayList<Show.Sources.Source>();
            }
            return this.source;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Source {

            @XmlAttribute
            protected Integer id;
            @XmlAttribute
            protected String type;
            @XmlAttribute
            protected String visibility;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the visibility property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVisibility() {
                return visibility;
            }

            /**
             * Sets the value of the visibility property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVisibility(String value) {
                this.visibility = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="thumbnail" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "thumbnail"
    })
    public static class Thumbnails {

        @XmlElement(required = true)
        protected List<Show.Thumbnails.Thumbnail> thumbnail;

        /**
         * Gets the value of the thumbnail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the thumbnail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getThumbnail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Show.Thumbnails.Thumbnail }
         * 
         * 
         */
        public List<Show.Thumbnails.Thumbnail> getThumbnail() {
            if (thumbnail == null) {
                thumbnail = new ArrayList<Show.Thumbnails.Thumbnail>();
            }
            return this.thumbnail;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Thumbnail {

            @XmlAttribute
            protected Integer width;
            @XmlAttribute
            protected Integer height;
            @XmlAttribute
            protected String type;

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWidth(Integer value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHeight(Integer value) {
                this.height = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

}
